//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eForm.Repository.SQLQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eForm.Repository.SQLQuery.InvoiceQuery", typeof(InvoiceQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT RequestNumber
        ///      ,DetailName
        ///      ,Qty
        ///      ,Rate
        ///      ,UoMID
        ///  FROM InvoiceDetail
        ///  WHERE RequestNumber = @RequestNumber.
        /// </summary>
        public static string GetInvoiceDetail {
            get {
                return ResourceManager.GetString("GetInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT RequestNumber
        ///      ,LanguageID
        ///      ,CurrencyID
        ///      ,InvoiceFrom
        ///      ,VendorID
        ///      ,InvoiceDate
        ///      ,Status
        ///      ,PoNumber
        ///      ,Discount
        ///      ,CreatedDate
        ///      ,CreatedBy
        ///  FROM InvoiceHeader
        ///  WHERE RequestNumber = @RequestNumber.
        /// </summary>
        public static string GetInvoiceHeader {
            get {
                return ResourceManager.GetString("GetInvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO InvoiceDetail
        ///           (RequestNumber
        ///           ,DetailName
        ///           ,Qty
        ///           ,Rate
        ///           ,UoMID)
        ///     VALUES
        ///           (@RequestNumber
        ///           ,@DetailName
        ///           ,@Qty
        ///           ,@Rate
        ///           ,@UoMID)
        ///
        ///
        ///.
        /// </summary>
        public static string InsertInvoiceDetail {
            get {
                return ResourceManager.GetString("InsertInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO InvoiceHeader
        ///           (RequestNumber
        ///           ,LanguageID
        ///           ,CurrencyID
        ///           ,InvoiceFrom
        ///           ,VendorID
        ///           ,InvoiceDate
        ///           ,Status
        ///           ,PoNumber
        ///           ,Discount
        ///           ,CreatedDate
        ///           ,CreatedBy)
        ///     VALUES
        ///           (@RequestNumber
        ///           ,@LanguageID
        ///           ,@CurrencyID
        ///           ,@InvoiceFrom
        ///           ,@VendorID
        ///           ,@InvoiceDate
        ///           ,@Status
        ///           ,@PoNumber
        ///           ,@Di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertInvoiceHeader {
            get {
                return ResourceManager.GetString("InsertInvoiceHeader", resourceCulture);
            }
        }
    }
}
