//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eForm.Repository.SQLQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterDataQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterDataQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eForm.Repository.SQLQuery.MasterDataQuery", typeof(MasterDataQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Name
        ///      ,Code
        ///  FROM MasterCurrency
        ///.
        /// </summary>
        internal static string GetAllMasterCurrency {
            get {
                return ResourceManager.GetString("GetAllMasterCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///  FROM MasterLanguage.
        /// </summary>
        internal static string GetAllMasterLanguage {
            get {
                return ResourceManager.GetString("GetAllMasterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///      ,Code
        ///  FROM MasterUoM.
        /// </summary>
        internal static string GetAllMasterUoM {
            get {
                return ResourceManager.GetString("GetAllMasterUoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///      ,ContactName
        ///      ,Address
        ///  FROM MasterVendor.
        /// </summary>
        internal static string GetAllMasterVendor {
            get {
                return ResourceManager.GetString("GetAllMasterVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT PONumber
        ///      ,Name
        ///  FROM PurchaseOrder.
        /// </summary>
        internal static string GetAllPurchaseOrder {
            get {
                return ResourceManager.GetString("GetAllPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT PONumber
        ///      ,Name
        ///  FROM PurchaseOrder
        ///  WHERE PONumber =  @PONumber.
        /// </summary>
        internal static string GetAllPurchaseOrderByNumber {
            get {
                return ResourceManager.GetString("GetAllPurchaseOrderByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Name
        ///      ,Code
        ///  FROM MasterCurrency
        ///  WHERE ID = @ID.
        /// </summary>
        internal static string GetMasterCurrencyByID {
            get {
                return ResourceManager.GetString("GetMasterCurrencyByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///  FROM MasterLanguage
        ///  WHERE ID = @ID.
        /// </summary>
        internal static string GetMasterLanguageByID {
            get {
                return ResourceManager.GetString("GetMasterLanguageByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///      ,Code
        ///  FROM MasterUoM
        ///  WHERE ID = @ID.
        /// </summary>
        internal static string GetMasterUoMByID {
            get {
                return ResourceManager.GetString("GetMasterUoMByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT ID
        ///      ,Name
        ///      ,ContactName
        ///      ,Address
        ///  FROM MasterVendor
        ///  WHERE ID = @ID.
        /// </summary>
        internal static string GetMasterVendorByID {
            get {
                return ResourceManager.GetString("GetMasterVendorByID", resourceCulture);
            }
        }
    }
}
